---

- name: install tools
  package: name=net-tools,traceroute,ifenslave,bridge-utils,iperf,tcpdump,iptables,gnupg

- name: ensure absence of classic /etc/network/interfaces
  file:
   path: /etc/network/interfaces
   state: absent

- name: set loopback ip
  template:
   src: loopback.network
   dest: /etc/systemd/network/00_loopback.network
  register: loopback

- name: configure interfaces participating in bgp
  template:
   src: bgp_interfaces.network
   dest: /etc/systemd/network/01_bgp_interfaces.network
  register: interfaces

- name: enable systemd-networkd
  service:
   name: systemd-networkd
   enabled: true

- name: disable classic networking
  service:
   name: networking.service
   enabled: false

- name: configure sysctls
  template:
   src: local.conf
   dest: /etc/sysctl.d/local.conf
  register: sysctl

- name: frr repo key
  ansible.builtin.apt_key:
   url: https://deb.frrouting.org/frr/keys.asc
   state: present

- name: frr repo
  ansible.builtin.apt_repository:
   repo: deb https://deb.frrouting.org/frr bullseye frr-stable
   state: present

- name: install frr
  package: name=frr,frr-pythontools

- name: configure frr
  template:
   src: frr.conf
   dest: /etc/frr/frr.conf
  register: conf

- name: configure frr daemons
  template:
   src: daemons
   dest: /etc/frr/daemons
   owner: frr
   group: frr
   mode: 0640
  register: daemons

- name: enable frr
  service:
   name: frr
   enabled: true
   state: started
  when: "'localhost' not in inventory_hostname"

- name: reboot
  reboot:
  when: "'localhost' not in inventory_hostname and ( conf.changed or daemons.changed or interfaces.changed or sysctl.changed or loopback.changed )"
