---

- name: install tools
  package: name=net-tools,traceroute,ifenslave,bridge-utils,iperf,tcpdump,iptables,gnupg

- name: ensure absence of classic /etc/network/interfaces
  file:
   path: /etc/network/interfaces
   state: absent

- name: set loopback ip
  template:
   src: loopback.network
   dest: /etc/systemd/network/00_loopback.network
  register: loopback

- name: declare interfaces list
  set_fact:
    interfaces: []

- name: reconcile interfaces to configure
  set_fact:
    interfaces: '{{interfaces + [item]}}'
  loop: "{{ansible_interfaces}}"
  when: "item not in reserved_ports and item|regex_search(\"^enp\") or item|regex_search(\"^eno\") or item|regex_search(\"^eth\")"

- name: configure physical interfaces on which to run bgpvlan
  template:
   src: bgpvlan_hw.network
   dest: /etc/systemd/network/01_bgpvlan_{{item}}_hw.network
  loop: "{{interfaces}}"

- name: create bgpvlan virtual interfaces
  template:
   src: bgpvlan.netdev
   dest: /etc/systemd/network/01_bgpvlan_{{item}}.netdev
  loop: "{{interfaces}}"

- name: configure bgpvlan virtual interfaces
  template:
   src: bgpvlan.network
   dest: /etc/systemd/network/01_bgpvlan_{{item}}.network
  loop: "{{interfaces}}"

- name: enable systemd-networkd
  service:
   name: systemd-networkd
   enabled: true

- name: disable classic networking
  service:
   name: networking.service
   enabled: false

- name: configure sysctls
  template:
   src: local.conf
   dest: /etc/sysctl.d/local.conf
  register: sysctl

- name: install frr
  package: name=frr,frr-pythontools

- name: configure frr
  template:
   src: frr.conf
   dest: /etc/frr/frr.conf
  register: conf

- name: configure frr daemons
  template:
   src: daemons
   dest: /etc/frr/daemons
   owner: frr
   group: frr
   mode: 0640
  register: daemons

- name: enable frr
  service:
   name: frr
   enabled: true
   state: started
  when: "'localhost' not in inventory_hostname"

- name: reboot
  reboot:
  when: "'localhost' not in inventory_hostname and ( conf.changed or daemons.changed or sysctl.changed or loopback.changed )"
