---

- name: install tools
  package: name=net-tools,traceroute,ifenslave,bridge-utils,iperf,tcpdump,iptables,frr-pythontools

- name: configure network
  template:
   src: interfaces
   dest: /etc/network/interfaces
  register: interfaces

- name: configure sysctls
  template:
   src: local.conf
   dest: /etc/sysctl.d/local.conf
  register: sysctl

- name: reboot
  reboot:
  when: sysctl.changed or interfaces.changed and ansible_hostname != localhost

- name: frr repo key
  ansible.builtin.apt_key:
   url: https://deb.frrouting.org/frr/keys.asc
   state: present

- name: frr repo
  ansible.builtin.apt_repository:
   repo: deb https://deb.frrouting.org/frr bullseye frr-stable
   state: present

- name: install frr
  package: name=frr

- name: configure frr
  template:
   src: frr.conf
   dest: /etc/frr/frr.conf
  notify: restart frr

- name: configure frr daemons
  template:
   src: daemons
   dest: /etc/frr/daemons
   owner: frr
   group: frr
   mode: 0640
  notify: restart frr

- name: enable frr
  service:
   name: frr
   enabled: true
   state: started
