---
- name: Install debian tools
  ansible.builtin.package:
    name: net-tools,traceroute,iperf,tcpdump,nmap,netplan.io
  when: ansible_os_family == 'Debian'

- name: Install rocky packages
  ansible.builtin.package:
    name: "{{ item }}"
  when: ansible_os_family == 'RedHat'
  with_items:
    - epel-release
    - systemd-networkd

- name: Declare interfaces list
  ansible.builtin.set_fact:
    interfaces: []

- name: Reconcile interfaces to configure
  ansible.builtin.set_fact:
    interfaces: "{{ interfaces + [item] }}"
  loop: "{{ ansible_interfaces }}"
  when: item not in reserved_ports and item|regex_search("^enp") or item|regex_search("^eno") or item|regex_search("^eth")

- name: ensure classic and systemd-networkd configs are absent
  ansible.builtin.file:
    state: absent
    path: '{{item}}'
  with_items:
    - /etc/systemd/network
    - /etc/network/interfaces
    - /etc/network/interfaces.d

- name: Ensure NetworkManager is disabled
  ansible.builtin.service:
    name: NetworkManager
    enabled: false
  when: ansible_os_family == 'RedHat'

- name: Enable systemd-networkd
  ansible.builtin.service:
    name: systemd-networkd
    enabled: true

- name: land netplan template
  ansible.builtin.template:
    src: netplan.yaml
    dest: /etc/netplan/bgp-unnumbered.yaml
    mode: 0600
  register: network

- name: Configure sysctls
  ansible.builtin.template:
    src: local.conf
    dest: /etc/sysctl.d/bgp-unnumbered.conf
    mode: 0644
  register: sysctl

- name: Install frr
  ansible.builtin.package:
    name: frr

- name: Configure frr
  ansible.builtin.template:
    src: frr.conf
    dest: /etc/frr/frr.conf
    mode: 0600
  register: conf

- name: Enable bgp
  ansible.builtin.lineinfile:
    path: /etc/frr/daemons
    regexp: ^bgpd=
    line: bgpd=yes

- name: Set ecmp path count
  ansible.builtin.lineinfile:
    path: /etc/frr/daemons
    regexp: ^bgpd_options=
    line: bgpd_options="   -A 127.0.0.1 --ecmp 2"
  register: daemons

- name: Enable frr
  ansible.builtin.service:
    name: frr
    enabled: true
    state: started
  when: "'localhost' not in inventory_hostname"

- name: Reboot
  ansible.builtin.reboot:
  when: "'localhost' not in inventory_hostname and ( conf.changed or daemons.changed or sysctl.changed or network.changed )"
