---
- name: Restart frr
  ansible.builtin.service:
    name: frr
    state: restarted
  listen: restart frr

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen: restart sshd
