name: tox

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: tox -e lint
      uses: docker://python:3.11
      with:
        entrypoint: bash
        args: |
          pip install tox
          tox -e lint
